auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("auctions/", views.index, name="index"),
    path("auctions/login", views.login_view, name="login"),
    path("auctions/logout", views.logout_view, name="logout"),
    path("auctions/register", views.register, name="register"),
    path("auctions/new_listing", views.NewListing, name="newlisting"),
    path("auctions/<int:listingid>", views.ListingPage, name="listingpage"),
    path("auctions/category/<int:catid>", views.CategoryListing, name="catlistings"),
    path("auctions/<int:listingid>/", views.AddComment, name="addcomment"),
    path("auctions/<int:listingid>/closed", views.CloseAuction, name="closeauction"),
    path("auctions/add_watchlist/<int:listingid>", views.AddWatchlist, name="addwatchlist"),
    path("auctions/my_watchlist/", views.MyWatchlist, name="watchlist"),
    path("auctions/my_listings/", views.MyListings, name="mylistings"),
    path("auctions/search/", views.Search, name="search")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", RedirectView.as_view(url='auctions/', permanent=True)),
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from django.forms import ModelForm, Textarea, TextInput
from datetime import datetime
import math
from django.utils.translation import ugettext_lazy as _

class User(AbstractUser):
    pass

    def __str__(self):
        return self.username.replace("_", " ").title()


class Category(models.Model):
    
    CATEGORY_CHOICES = [
        ('Fashion', 'Fashion'),
        ('Electronics', 'Electronics'),
        ('Toys & Collectibles', 'Toys & Collectibles'),
        ('Books, Movies & Music','Books, Movies & Music')
    ]

    name = models.CharField(max_length=21, choices=CATEGORY_CHOICES)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Condition(models.Model):
    
    CONDITION_CHOICES = [
        ('New', 'New'),
        ('Used', 'Used')
    ]

    name = models.CharField(max_length=4, choices=CONDITION_CHOICES)

    def __str__(self):
        return self.name


class Listing(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=25)
    description = models.CharField(max_length=100)
    image = models.CharField(max_length=200, default="https://raw.githubusercontent.com/SammanthaPS/Images/main/1613805338636.png", blank=True)
    starting_bid = models.DecimalField(max_digits=8, decimal_places=2, default=5.00)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    condition = models.ForeignKey(Condition, on_delete=models.SET_NULL, null=True)
    created_on = models.TimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
class ListingForm(ModelForm):
    class Meta:
        model = Listing
        widgets = {
            'description': Textarea(attrs={'cols': 50, 'rows': 4}),
        }
        exclude = ['user', 'created_on', 'active']


class Bid(models.Model):
    bid = models.DecimalField(max_digits=8, decimal_places=2, default=1.00)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    created_on = models.TimeField(auto_now_add=True, blank=True)
    
class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['bid',]


class Comment(models.Model):
    title = models.CharField('title', max_length=30)
    comment = models.CharField(max_length=100)
    created_on = models.DateField(default=datetime.now, blank=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE) 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        widgets = {
            'comment': Textarea(attrs={'cols': 50, 'rows': 4}),
    }
        exclude = ['created_on', 'listing', 'user']


class Watchlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.db.models import Max, Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .models import *


def index(request):
    listings = Listing.objects.filter(active=True).order_by('title')
    return render(request, "auctions/index.html", {
        'listings':listings
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/login.html", {
                "alert": "Error! Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/login.html", {
                "alert": "Error! Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/login.html")


@login_required(login_url='login')
def NewListing(request):
    # will create a new listing.
    if request.method == "POST":
        form = ListingForm(request.POST)
        if form.is_valid():
            Listing = form.save(commit=False) # create but don't save on database
            Listing.user = request.user # request the current user
            Listing.save() # save to the database

            return render(request, "auctions/newlisting.html", {
                'message':True
            })
        else:
            return render(request, "auctions/newlisting.html")
    else:
        return render(request, 'auctions/newlisting.html')


def ListingPage(request, listingid):
    # will render a page with details of a listing.
    listing = Listing.objects.get(id=listingid)
    comments = Comment.objects.filter(listing=listing)

    def activelisting():
        if listing in Listing.objects.filter(active=True):
            return True
        else:
            return False
    

    def addedwatchlist():
        user = request.user
        added = Watchlist.objects.filter(user=user, listing=listing)
        if added:
            return True
        else:
            return False

    def maxvalue():
        bid = Bid.objects.filter(listing=listing)
        if bid:
            currentbid = float(Bid.objects.filter(listing=listing).aggregate(Max('bid'))['bid__max'])
            maxbid_user = Bid.objects.get(bid=currentbid).user
            return currentbid, maxbid_user
        else:
            return listing.starting_bid, listing.user


    # if empty comments
    def emptycomments():
        if len(comments) == 0:
            return True
        else:
            return False
    

    # returning multiple values from a function.
    a, b = maxvalue()

    # form to place bid
    if request.method == 'POST':
        form = BidForm(request.POST)
        placebid = form.save(commit=False)
        placebid.user = request.user
        placebid.listing = Listing.objects.get(id=listingid)
        
        if a >= placebid.bid:
            return render(request, "auctions/listingpage.html", {
                'alert': True,
                'listing': listing,
                'comments': comments,
                'active': activelisting, 
                'emptycomments': emptycomments,
                'bid': a,
                'maxbiduser': b,
                'added': addedwatchlist,
            })
        else:
            # delete previous bid from the current user.
            #user = request.user
            previousbids = Bid.objects.filter(user=placebid.user, listing=listing)
            previousbids.delete()

            # save new bid
            placebid.save()
            if not Watchlist.objects.filter(user=request.user, listing=listing):
                Watchlist(listing=listing, user=request.user).save() # automatically save to watchlist when place a bid.

            currentbid = float(Bid.objects.filter(listing=listing).aggregate(Max('bid'))['bid__max'])
            maxbid_user = Bid.objects.get(bid=currentbid).user
            return render(request, "auctions/listingpage.html", {
                'success': True,
                'listing': listing,
                'comments': comments,
                'active': activelisting,
                'emptycomments': emptycomments,
                'bid': currentbid,
                'maxbiduser': maxbid_user,
                'added': addedwatchlist,
            })
    else:
        return render(request, "auctions/listingpage.html", {
        'listing': listing,
        'comments': comments,
        'active': activelisting,
        'winner': b,
        'emptycomments': emptycomments,
        'bid': a,
        'maxbiduser': b,
        'added': addedwatchlist,
    })


@login_required(login_url='login')
def AddComment(request, listingid):
    # will create a new comment.
    form = CommentForm(request.POST)
    addcomment = form.save(commit=False)
    addcomment.user = request.user
    addcomment.listing = Listing.objects.get(id=listingid)
    addcomment.save()
    return redirect(reverse("listingpage", args=[listingid]))


def CategoryListing(request, catid):
    categories = Category.objects.get(id=catid)
    listings = Listing.objects.filter(active=True, category=categories).order_by('title')
    return render(request, "auctions/index.html", {
        'listings': listings
    })


def CloseAuction(request, listingid):
    listing = Listing.objects.get(id=listingid)
    listing.active = False
    listing.save()
    return redirect(reverse("listingpage", args=[listingid]))


def AddWatchlist(request, listingid):
    user = request.user
    listing = Listing.objects.get(id=listingid)
    
    if Watchlist.objects.filter(user=user, listing=listing):
        Watchlist.objects.filter(user=user, listing=listing).delete()
        return redirect(reverse("listingpage", args=[listingid]))
    else:
        Watchlist(listing=listing, user=user).save()
        return redirect(reverse("listingpage", args=[listingid]))


def MyWatchlist(request):
    user = request.user
    mywatchlist = Watchlist.objects.filter(user=user)

    def emptywatchlist():
        if len(mywatchlist) == 0:
            return True
        else:
            return False

    return render(request, "auctions/watchlist.html", {
        'listings': mywatchlist,
        'empty': emptywatchlist,
    })


def MyListings(request):
    listings = Listing.objects.filter(user=request.user)

    def emptylisting():
        if len(listings) == 0:
            return True
        else:
            return False


    return render (request, "auctions/mylistings.html", {
        'listings': listings,
        'empty': emptylisting,
    })


def Search(request):
    searchform = request.GET.get("q")
    category = request.GET.get("category")

    if category:
        listings = Listing.objects.filter(Q(category=category, title__icontains=searchform) | Q(category=category, description__icontains=searchform))
    else:
        listings = Listing.objects.filter(Q(title__icontains=searchform) | Q(description__icontains=searchform))
 
    return render(request, "auctions/index.html", {
        'listings': listings,
    })

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}


{% block content %}

    <div id="card-content">
        <div id="card-background">
            <img src="{% static 'auctions/Images/card.png' %}">
        </div>
    </div>

{% endblock %}

{% block body %}

    {% for list in listings %}
        <div id="l-c"> <!--Listing Cards-->
            <div id="c-c"> <!--Card Content-->

                <div id="c-img">
                    <div>
                        <a href="{% url 'listingpage' list.id %}">
                            <img src="{{ list.image }}">
                        </a>        
                    </div>
                </div>

                <div id="c-title">
                    <a href="{% url 'listingpage' list.id %}">
                        {{ list.title }}
                    </a>
                </div>

                <div id="c-description">
                    "{{ list.description }}"
                </div>

                <div id="c-seller">
                    Seller: {{ list.user }}
                </div>

                <div id="c-bid">
                    ${{ list.starting_bid }}
                </div>

            </div>
        </div>
    {% endfor %}

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}E-Auction{% endblock %}</title>
        <link href="{% static 'auctions/CSS/styles.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'auctions/Images/shield.png' %}">
    </head>
    <body>

        <div class="navbar">
            <div class="img">
                <a href="{% url 'index' %}">
                    <img src="{% static 'auctions/Images/shield.png' %}" alt="E-Auction">
                </a>
            </div>
            
            <div class="search">
                <form action="{% url 'search' %}" method="GET">
                    <div>
                        <input class="text" type="text" name="q" placeholder="Search for anything">
                        <select class="categories" name="category">
                            <option value="">All categories</option>
                            <option value="1">Fashion</option>
                            <option value="2">Electronics</option>
                            <option value="3">Toys & Collectibles</option>
                            <option value="4">Books, Movies and Music</option>
                        </select>
                    </div>
                    <input class="submit" type="submit" name="btn" value="Search">    
                </form>
            </div>

            <div class="nav">
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <a class="dropbtn" href="#">
                            <img src="{% static 'auctions/Images/user.png' %}">
                        </a>
                        <div class="dropdown-content">
                            <a id="signed-as" href="#">{{ request.user }}</a>
                            <a href="{% url 'mylistings' %}">My Listings</a>
                            <a href="{% url 'newlisting' %}">New Listing</a>
                            <a href="{% url 'watchlist' %}">Watchlist</a>
                            <a id="logout" href="{% url 'logout' %}">Log Out</a>
                        </div>

                    </div>
                {% else %}
                    <a href="{% url 'login' %}">Log In | Register</a>
                {% endif %}
            </div>

        </div>

        <div class="go-category">
            <a href="{% url 'catlistings' catid=1 %}">Fashion</a>
            <a href="{% url 'catlistings' catid=2 %}">Electronics</a>
            <a href="{% url 'catlistings' catid=3 %}">Toys & Collectibles</a>
            <a href="{% url 'catlistings' catid=4 %}">Books, Movies & Music</a>
        </div>

        <div>

            {% block content %}
            {% endblock %}

            {% block body %}
            {% endblock %}  

        </div>
        
    </body>
</html>

auctions/templates/auctions/listingpage.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block body %}

    <div id="message-bid">
        {% if alert %}
            <div id="bid-alert-message">
                Error! Your bid should be greater than the current bid.
            </div>
        {% elif success %}
            <div id="bid-success-message">
                Yay! Your bid was successfull.
            </div>
        {% endif %}
    </div>

    <div class="listing-info">

        <div class="info-img">
            <div class="info-img-img">
                <img src="{{ listing.image }}">
            </div>
        </div>

        <div class="info">

            <div class="ititle">{{ listing.title }}</div>

            <div class="icondcat">
                {% if active %}
                    <div><span>Condition: </span>{{ listing.condition }}</div>
                    <div><span>Category: </span>{{ listing.category }}</div>
                    <div><span>Seller: </span>{{ listing.user }}</div>
                    <div><span>Starting bid: </span>${{ listing.starting_bid }}</div>
                {% else %}
                    {% if request.user != winner %}
                        <div class="bidquote">Going once, going Twice, sold! Auction Closed! </div>
                        <div class="winnerquote">Congratulations, {{ winner }}!</div>
                    {% else %}
                        <div class="bidquote">Going once, going Twice, sold!</div>
                        <div class="winnerquote">Congratulations! You Won!</div>
                        <div class="winnerimage"><img src="{% static 'auctions/Images/winner.png' %}"></div>
                    {% endif %}
                    <div class="finalprice"><span>Final Price: </span>${{ bid|floatformat:2 }}</div>
                {% endif %}

            </div>
            {% if active %}
                <div class="idescription">"{{ listing.description }}"</div>
                <div class="ibid"><span>Current Bid: </span>${{ bid|floatformat:2 }}<span id="bid-from"> from {{ maxbiduser }}</span></div>
            {% endif %}

            <div class="ibtn">
                {% if user.is_authenticated %}
                    {% if active %}
                        {% if request.user != listing.user %}
                            <form action="{% url 'listingpage' listing.id %}" method="POST">
                                {% csrf_token %}
                                <div id="bid-form">
                                    <div>
                                        <span>$</span>
                                        <input id="id_bid" name="bid" type="number" value="{{ bid|floatformat:2 }}" step="0.01" max="1000000" required>
                                    </div>
                                    <div id="btn-place-bid">
                                        <input id="id_btn-bid" type="submit" value="Place Bid">    
                                    </div>    
                                </div>
                            </form>
                            {% if added %}
                                <a href="{% url 'addwatchlist' listing.id %}"><button>Remove from Watchlist</button></a>
                            {% else %}
                                <a href="{% url 'addwatchlist' listing.id %}"><button>Add to Watchlist</button></a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'closeauction' listing.id %}"><button type="submit">Close Bid</button></a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </div>

    </div>

    <div>
        <div id="comments">Comments</div>
        {% if user.is_authenticated %}<!-- User need to be logged to see comments. -->
            {% if active %}
                <div><!-- form to add a comment. -->
                    {% if request.user != listing.user %}
                        <form id="commentform" action="{% url 'addcomment' listing.id %}" method="POST">
                            <div id="section-title">Leave a comment!</div>
                            {% csrf_token %}
                            <div id="comment-title">
                                <input id="id-comment-title" type="text" name="title" placeholder="Subject" maxlength="30" required>
                            </div>
                
                            <div id="comment-comment">
                                <textarea id="id-comment-comment" name="comment" placeholder="Write your comment here." cols="50" rows="4" maxlength="100" required></textarea>
                            </div>

                            <div id="button">
                                <input id="btn-create" type="submit" value="Submit">
                            </div>
                        </form>
                    {% endif %}
                </div>
            {% endif %}

            {% if emptycomments %}
                <div id="emptysection">
                    <img src="{% static 'auctions/Images/nocomments.png' %}" width="360px">
                </div>
            {% else %}
                {% for comment in comments %}
                    <div id="comment-section">
                        <div id="commentUser">{{ comment.user }}<span> - Verified User - {{ comment.created_on }}</span></div>
                        <div id="commentTitle">{{ comment.title }}</div>
                        <div id="commentText">{{ comment.comment }}</div>
                    </div>
                {% endfor %}
            {% endif %}
        {% else %}
            <div id="loginrequired">
                <img src="{% static 'auctions/Images/loginrequired.png' %}" width="500px">
            </div>         
        {% endif %}
    </div>
{% endblock %}

auctions/templates/auctions/mylistings.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block body %}

    <div id="watchlist-body">
        {% if empty %}

        <div class="emptywatchlist">
            <img src="{% static 'auctions/Images/EmptyListing.png' %}">
        </div>

        {% else %}
            {% for list in listings %}
                <div id="l-c">
                    <div id="c-c">

                        <div id="c-img">
                            <div>
                                <a href="{% url 'listingpage' list.id %}">
                                    <img src="{{ list.image }}">
                                </a>        
                            </div>
                        </div>

                        <div id="c-title">
                            <a href="{% url 'listingpage' list.id %}">
                                {{ list.title }}
                            </a>
                        </div>
                        {% if list.active %}
                            <div id="c-description">
                                "{{ list.description }}"
                            </div>

                            <div id="c-seller">
                                Seller: {{ list.user }}
                            </div>

                            <div id="c-bid">
                                ${{ list.starting_bid }}
                            </div>
                        {% else %}
                            <div>
                                <div id="closed-auction">Auction Closed!</div>
                            </div>
                        {% endif %}
                    </div>
                </div>

            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

auctions/templates/auctions/newlisting.html
{% extends "auctions/layout.html" %}

{% block body %}
        <div>
            {% if message %}
                <div>Listing Saved!</div>
            {% endif %}
        </div>

        <div id="new-listing">

            <div id="form">

                <form action="{% url 'newlisting' %}" method="POST">
                    <h4>New Listing</h4>

                    {% csrf_token %}                                            
                    <div id="title">
                        <span>TITLE</span>
                        <input id="id_title" type="text" name="title" maxlength="25" autofocus required>
                    </div>

                    <div id="description">
                        <div>DESCRIPTION</div>
                        <textarea id="id_description" name="description" cols="50" rows="4" maxlength="100" required></textarea>
                    </div>

                    <div id="image">
                        IMAGE
                        <input id="id_image" type="text" name="image" maxlength="200" value="https://gitcdn.link/repo/SammanthaPS/Images/main/noimage.png">
                    </div>

                    <div id="starting_bid">
                        STARTING BID $
                        <input id="id_starting_bid" name="starting_bid" type="number" value="5.00" step="0.01" max="1000000" required>
                    </div>

                    <div id="category">
                        <div>CATEGORY</div>
                        <select id="id_category" name="category" required>
                            <option value="">Select a Category</option>
                            <option value="1">Fashion</option>
                            <option value="2">Electronics</option>
                            <option value="3">Toys & Collectibles</option>
                            <option value="4">Books, Movies & Music</option>
                        </select>
                    </div>

                    <div id="condition">
                        <div>CONDITION</div>
                        <select id="id_condition" name="condition" required>
                            <option value="">Select a Condition</option>
                            <option value="1">New</option>
                            <option value="2">Used</option>
                        </select>
                    </div>
                    
                    <div id="button">
                        <input id="btn-create" type="submit" value="CREATE LISTING">
                    </div>

                </form>
    
            </div>
        </div>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}
{% load static %}



{% block body %}

    <div id="watchlist-body">
        {% if empty %}

        <div class="emptywatchlist">
            <img src="{% static 'auctions/Images/EmptyListing.png' %}">
        </div>

        {% else %}
            {% for list in listings %}
                <div id="l-c">
                    <div id="c-c">

                        <div id="c-img">
                            <div>
                                <a href="{% url 'listingpage' list.listing.id %}">
                                    <img src="{{ list.listing.image }}">
                                </a>        
                            </div>
                        </div>

                        <div id="c-title">
                            <a href="{% url 'listingpage' list.listing.id %}">
                                {{ list.listing.title }}
                            </a>
                        </div>
                        {% if list.listing.active %}
                            <div id="c-description">
                                "{{ list.listing.description }}"
                            </div>

                            <div id="c-seller">
                                Seller: {{ list.listing.user }}
                            </div>

                            <div id="c-bid">
                                ${{ list.listing.starting_bid }}
                            </div>
                        {% else %}
                            <div>
                                <div id="closed-auction">Auction Closed!</div>
                            </div>
                        {% endif %}
                    </div>
                </div>

            {% endfor %}
        {% endif %}

    </div>

{% endblock %}